export const routes = {
  home: '/home',
  onboarding: '/onboarding',
  order: '/order',
  shipment: '/shipment',
  manage:'/manage',
  packageTypes: '/manage/package-type',
  pickupLocation: '/manage/location',
  users: '/manage/user',
  stores: '/manage/store'
};

export const messages = {
  emailRequired: 'Email is required',
  passwordRequired: 'Password is required',
  confirmPasswordRequired: 'Confirm password is required',
  invalidCredentials: 'Invalid email address',
  invalidEmail: 'Invalid email',
  incorrectCredentials: 'Incorrect credentials',
  invalidPassword: "Invalid password",
  firstNameRequired: 'First name is required',
  lastNameRequired: 'Last name is required',
  bussinessNameRequired: 'Business name is required',
  mobileRequired: 'Mobile no. is required',
  invalidFirstName: 'Invalid first name',
  invalidLastName: 'Invalid last name',
  invalidBussinessName: 'Invalid business name',
  invalidMobile: 'Invalid mobile no.',
  invalidMobileNumber: 'Invalid mobile number',
  acceptTermsAndAgreements: 'Please accept Terms & Agreements',
  accountAlreadyExist: 'Account already exists',
  successfullSignUp: 'Successfully signed up. Please check your email',
  accountCreatedText: 'Account created for ',
  proceedToLoginText: 'Please proceed to login using the email',
  userNotFound: 'User not found',
  passwordMismatchError: 'Password and confirm password are not same',
  nameIsRequired: 'Name is required',
  weightGreaterThan: 'Weight must greater than 0.01',
  lenghtGreaterThan: 'Length must greater than 0.01',
  widthGreaterThan: 'Width must greater than 0.01',
  heightGreaterThan: 'Height must greater than 0.01',
  priceGreaterThan: 'Price must be greater than 0.01',
  invalidShipmentItems: 'Invalid shipment items',
  minTwoCharacter: 'Minimum 2 characters required',
  minSixCharacter: 'Minimum 6 characters required',
  minFiveCharacter: 'Minimum 5 characters required',
  maxFourItem: 'A maximum of 4 items are allowed',
  mobilenumberRequired: 'Mobile number is required',
  indianAddress1Required: 'Flat, house no., building, apt is required',
  indianAddress2Required: 'Area, street, sector, village is required',
  pincodeRequired: 'Pincode is required',
  cityRequired: 'City is required',
  stateRequired: 'State is required',
  packageRequired: 'Packages are required',
  morePackagesForB2B: 'First package added, add more packages only if you intend to do a B2B shipment.',
  weightMismatchError: 'Package weight must be equal or greater than combined items weight of 500 g',
  packageDeleteSuccess: 'Package has been deleted successfully',
  shipmentCreatedSuccessfully:'Shipment created, tracking details will be updated as we get new notifications.',
  orderCreatedSuccessfully:'Order has been saved successfully',
  orderDiscardedSuccessfully: 'Order has been discarded successfully',
  orderImportedSuccessfully: 'The file is uploaded successfully and contains 6 records.',
  packageTypesSavedSuccessfully: 'Package type added successfully',
  packageTypesUpdatedSuccessfully:'Package type updated successfully',
  packageTypesDeletedSuccessfully: 'Your package type has been deleted successfully',
  pickupLocationSavedSuccessfully: 'Pickup location has been added successfully',
  pickupLocationUpdatedSuccessfully: 'Pickup location has been updated successfully',
  pickupLocationDeletedSuccessfully: 'Pickup location has been deleted successfully',
  userSavedSuccessfully:'New user created successfully',
  userUpdatedSuccessfully: 'User updated successfully',
  userDeletedSuccessfully: 'User has been deleted successfully',
  storeCreatedSuccessfully: 'Store created successfully',
  storeUpdatedSuccessfully: 'Store updated successfully',
  storeDeletedSuccessfully: 'Store deleted successfully',
  invoiceRequiredForB2B: 'Invoice is required for Domestic B2B shipment'
};

export const label = {
  login: 'Login',
  forgotPasswordQuestionMark: 'Forgot password?',
  forgotPassword: 'Forgot password',
  register: 'Register now',
  password: 'Password',
  email: 'Email',
  firstName: 'First name',
  lastName: 'Last name',
  bussinessName: 'Business name',
  mobile: 'Mobile number',
  acceptTermsAndAgreements: 'Accept Terms & Agreements',
  registerAccount: 'Register account',
  sendEmail: 'Send Email',
  backToLogin: 'Back to login',
  resetPassword: 'Reset password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  orders: 'Orders',
  allOrders: 'All orders',
  store: 'Store',
  orderType: 'Order type',
  orderStatus: 'Order status',
  date: 'Date',
  shipmentStatus: 'Shipment status',
  orderNumber: 'Order number',
  orderItem: 'Order item (s)',
  orderValue: 'Order value',
  id: 'ID',
  sort: 'Sort',
  customerName: 'Customer name',
  paymentType: 'Payment type',
  saveAndContinue: 'Save & Continue',
  back: 'Back',
  name: 'Name',
  price: 'Price',
  weigth: 'Weight',
  qty: 'Qty',
  shipmentItems: 'Shipment items',
  recipeintaddress: 'Recipient address',
  country: 'Country',
  landmark: 'Landmark',
  pincode: 'Pincode',
  city: 'City',
  State: 'State',
  locationForSameDay: 'Location for same day rates:',
  add:'Add',
  edit: 'Edit',
  remove: 'Remove',
  saveOrder: 'Save order',
  backToItems: 'Back to items',
  indianAddress1: 'Flat, house no., building, apartment',
  indianAddress2: 'Area, street, sector, village',
  backToRecipient: 'Back to recipient',
  units: 'Units',
  packages: 'Packages',
  specialServices: 'Special services',
  insurance: 'Insurance',
  cod: 'COD',
  hazmat: 'HAZMAT',
  liquidContent: 'Liquid content',
  fragile: 'Fragile',
  otpRequired: 'OTP required',
  type: 'Type',
  length: 'Length',
  width: 'Width',
  height: 'Heigth',
  backToPackaging: 'Back to packaging',
  backToCarrier: 'Back to carrier',
  backToCompliance: 'Back to compliance',
  createShipment: 'Create shipment',
  items: 'ITEMS',
  addresses: 'Addresses',
  packagingAndCarrier: 'PACKAGING & CARRIER',
  tracking: 'TRACKING',
  box: 'Box',
  weight: 'Weight',
  billableWeight: 'Billable weight',
  edd: "EDD",
  supportContacts: 'Support contacts',
  totalFee: 'Total Fee',
  pickupLocation: 'Pickup location',
  trackingNumber: 'Tracking number',
  cloneOrder: 'Clone order',
  moreOptions: 'More options',
};

export const appConstant = {
  kloudshipHyphenCyrpess: 'KloudShip-Cypress',
  yopmail: '@yopmail.com',
  invalidFormatEmailId: 'invalidFormat@email',
  ord: 'ORD',                          
  hypen: '-',                          
  space: '',
};

export const cyAssertion = {
  exist: 'exist',
  beVisible: 'be.visible',
  contains: 'contain',
  include: 'include',
  haveAttribute: 'have.attr',
  src: 'src',
  href: 'href',
  text: 'text',
  prop: 'prop',
  innerText: 'innerText',
  dragDrop: 'drag-drop',
  placeholder: 'placeholder'
};

export const url = {
  kloudshipLogo: 'https://kloudship-public-assets.s3.amazonaws.com/logo-ks-right-tran.png',
  loginImage: 'https://kloudship-public-assets.s3.amazonaws.com/ECSLite/img-login.png',
  signUpImage: 'https://kloudship-public-assets.s3.amazonaws.com/ECSLite/img-register.png',
  termsAndAgreements: 'https://www.kloudship.com/terms-agreements/',
  forgotPasswordImage: 'https://kloudship-public-assets.s3.amazonaws.com/ECSLite/img-forgot-password.png',
  yopmailURL: 'https://yopmail.com/en/',
};

export const infoText = {
  enterYourEmailToResetPassword: 'Please enter your email address to reset password. We will send reset password link',
  resetPasswordEmailSent: 'Check your email. You should receive an email from us shortly to reset your password',
  resetPasswordEmailSentText: 'We just sent an email to',
  resetPasswordInstructions: 'Click the secure link we sent you to reset your password. If you didn\'t receive an email, please check your spam folder.',
  orderSearch: 'Search by customer name, order number, order code',
  orderGeneralInfoCard1Text1: 'Specify your order type to see relevant controls on following steps.',
  orderGeneralInfoCard1Text2: 'Order number is required only if you want to map your external order numbers to KloudShip orders.',
  orderGeneralStepperHeader: 'What would you like to ship today?',
  orderAddressStepperHeader: 'To where, you would like to ship your item(s)?',
  orderPackagingStepperHeader: 'Few more details, before we ship this package!',
  orderPackagingInfoCard: 'You may search all package types by name, or quickly view your Recently shipped and Favourite package types.',
  orderPackagingSpecialServiceInfoCard: 'Special services are additional option which you can request or gets auto applied based upon the specified items. You are highly encouraged to provide correct declaration and choose desired special services as per your business need. Since all carriers do not support all special service, you may see reduced carriers on next page when you select them.',
  orderCarrierStepperHeader: 'Who will deliver this shipment?',
  orderReviewStepperHeader: 'Quick Review, before the shipment is created',
  userDeletedMailContent: "User account deleted!"
};

export const fixture = {
  authenticationJSON: 'authentication.json',
  orderJSON: 'order.json',
  orderImportJSON: 'import-sample-data-order.json',
  orderImportCSV: 'import-sample-data-order.csv',
  manageJSON: 'manage.json',
  invoicePDF: 'sample-invoice.pdf'
};

export const keyboardKeys = {
  enterKey: "{enter}"
};