export const selector = {
    
    loginPage: {
        logoLocator: '#login-content > :nth-child(1) > .w-fulljustify-start > .h-10',
        loginImageLocator: '#login-content > [class*="md:flex"] > .mt-4',
        emailInputLocator: '#login-email',
        passwordInputLocator: '#login-password',
        loginButtonLocator: '#login-btn',
        forgotPasswordLocator: '.mb-6 > .link-color',
        registerLocator: '#login-form > .mt-4 > .link-color',
        loginHeaderLocator: '#login-content > :nth-child(1) > .flex-col > .w-72 > .text-2xl',
        emailTitleLocator: '#login-form > :nth-child(1) > .block',
        passwordTitleLocator: '#login-form > .mb-3.relative > .block',
        emailErrorLocator: '#login-email-error',
        passwordErrorLocator: '#login-password-error',
        notificationAlertLocator: '#alert-message > li',
    },
    signupPage: {
        logoLocator: '#signup-content > :nth-child(1) > .w-fulljustify-start > .h-10',
        signUpImageLocator: '.signup-image-container > .mt-4',
        registerLocator: '#login-form > .mt-4 > .link-color',
        registerAccountHeaderLocator: '#signup-content > :nth-child(1) > .flex-col > .mb-8 > .text-2xl',
        firstNameTitleLocator: '.mr-1 > .block',
        firstNameInputLocator: '#signup-first-name',
        lastNameTitleLocator: '.ml-1 > .block',
        lastNameInputLocator: '#signup-last-name',
        bussinessTitleLocator: '#signup-form > :nth-child(2) > .block',
        bussinessNameInputLocator: '#signup-company-name',
        mobileTitleLocator: ':nth-child(3) > .block',
        mobileInputLocator: '#signup-contact-phone',
        emailTitleLocator: ':nth-child(4) > .block',
        emailInputLocator: '#signup-email',
        passwordTitleLocator: '.mb-2.relative > .block',
        passwordInputLocator: '#signup-password',
        acceptTermsAndAgreementsLocator: '#signup-form > .mb-3 > .text-sm',
        checkBoxLocator: '#term-condition-checkbox',
        registerAccountButtonLocator: '#signup-btn',
        loginButtonLocator: '.text-gray-900.mt-2 > .link-color',
        firstNameErrorLocator: '#signup-first-name-error',
        lastNameErrorLocator: '#signup-last-name-error',
        bussinessNameErrorLocator: '#signup-company-name-error',
        mobileErrorLocator: '#signup-contact-phone-error',
        emailErrorLocator: '#signup-email-error',
        passwordErrorLocator: '#signup-password-error',
        notificationAlertLocator: '#alert-container > .relative',
        accountCreatedTextLocator: '.mt-10',
        signUpBusinessNameLocator: '#signup-company-name-text',
        signUpEmailLocator: '#signup-email-text',
        proceedToLoginTextLocator: '#signup-success-detail > :nth-child(2)',
        signUpSucessLoginLocator: '#signup-success-detail > .absolute > .flex'
    },
    forgotPasswordPage: {
        logoLocator: '#forgot-password-content > :nth-child(1) > .w-fulljustify-start > .h-10',
        forgotPasswordImageLocator: '#forgot-password-content > [class*="md:flex"] > .mt-4',
        forgotPasswordHeaderLocator: '.w-80 > .text-2xl',
        enterEmailTextLocator: '#forgot-password-info-detail',
        emailTitleLocator: '#forgot-password-form > :nth-child(1) > .block',
        emailInputLocator: '#forgot-password-email',
        sendEmailButtonLocator: '#forgot-password-btn > span',
        backToLoginLocator: '#back-to-login-link > a',
        emailErrorLocator: '#forgot-password-email-error',
        notificationAlertLocator: '#alert-container > .relative',
        resetPasswordEmailSentTextLocator: '#forgot-password-success-detail > p.text-gray-600.text-sm.my-2',
        resetPasswordEmailLocator: '#forget-password-email-text',
        resetPasswordInstructionsLocator: '#forgot-password-success-detail > p.text-gray-600.text-sm.my-6',
        resetPasswordMailButtonLocator: 'a:contains("Reset Password")',
        resetPasswordLogoLocator: '#reset-password-content > :nth-child(1) > .w-fulljustify-start > .h-10',
        resetPasswordImageLocator: '#reset-password-logo',
        resetPasswordHeaderLocator: '#reset-password-title',
        newPasswordTitleLocator: '#reset-password-form > :nth-child(1) > .block',
        newPasswordInputLocator: '#reset-password-new',
        confirmPasswordTitleLocator: '#reset-password-form > :nth-child(2) > .block',
        confirmPasswordInputLocator: '#reset-password-confirm',
        resetPasswordButtonLocator: '#reset-password-btn-text',
        newPasswordRequiredErrorLocator: '#reset-password-new-error',
        confirmPasswordRequiredErrorLocator: '#reset-password-confirm-error',
        passwordMismatchErrorLocator: '#reset-password-confirm-error',
    },
    yopMailPage: {
        emailInputLocator: '#login',
        emailHtmlLocator: '#ifmail',
        readIframeHTML: '0.contentDocument.body',
    },
    sideNav: {
        hamburgerMenuLocator: '.pl-16',
        orderNavigation: ':nth-child(2) > .MuiListItem-root > .MuiButtonBase-root > .display-flex-justify-space-between > .display-flex-align-center > .MuiTypography-root',
        shipmentNavigation: ':nth-child(3) > .MuiListItem-root > .MuiButtonBase-root > .display-flex-justify-space-between > .display-flex-align-center > .MuiTypography-root',
        manageNavigation: ':nth-child(2) > .display-flex > .MuiListItem-root > .MuiButtonBase-root > .display-flex-justify-space-between'
    },
    header:{
        profilButtonLocator: '#root > div > div:nth-child(1) > header > div.MuiToolbar-root.MuiToolbar-gutters.MuiToolbar-regular.header-toolbar.css-jn6sib > button',
        logoutButtonLocator: '#custom-menu > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation0.MuiPopover-paper.MuiMenu-paper.MuiMenu-paper.css-1dgjnic > ul > div:nth-child(2) > li > div'
    },
    popUp:{
        confirmButtonLocator: '.MuiButton-contained > .MuiTypography-root',
        shipmentNavigation: ':nth-child(3) > .MuiListItem-root > .MuiButtonBase-root > .display-flex-justify-space-between > .display-flex-align-center > .MuiTypography-root'
    },
    orderList: {
        titleLocator: '.main-card-header > .MuiTypography-root',
        allOrdersTabLocator: '.css-xr0bbm',
        searchFilterLocator: 'input[placeholder="Search by customer name, order number, order code"]',
        storeFilterLocator: ':nth-child(1) > .MuiInputBase-root > .MuiSelect-select > .MuiButtonBase-root > .MuiTypography-root',
        orderTypeFilterLocator: ':nth-child(2) > .MuiInputBase-root > .MuiSelect-select > .MuiButtonBase-root > .MuiTypography-root',
        dateFilterLocator: '[label="Date"]',
        sortFilterLocator: '[label="Sort"] > .MuiTypography-root',
        idColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(1)',
        customerNameColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(2)',
        storeColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(3)',
        orderNumberColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(4)',
        orderItemColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(5)',
        orderValueColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(6)',
        orderTypeColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(7)',
        orderStatusColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(8)',
        shipmentStatusColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(9)',
        dateColumnLocator: '.MuiTableHead-root > .MuiTableRow-root > :nth-child(10)',
        addOrderButtonLocator: '.MuiButton-contained',
        importButtonLocator: '[label="Import"]',
        firstOrderInListLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.tab-list-container.MuiBox-root.css-0 > div > div.MuiTableContainer-root.tab-list-table-container.css-kge0eu > table > tbody > tr:nth-child(1)'
    },
    orderGeneralStepper: {
        headerLocator: '.css-43ob0e',
        iconLocator: '[label="General"] > .MuiButtonBase-root > .MuiStepLabel-root > .MuiStepLabel-labelContainer > .MuiStepLabel-label',
        saveAndContinueButtonLocator: '.custom-stepper-header-action-button > .MuiButtonBase-root',
        imageSelectorLocator: '.css-0 > img',
        infoCard1Text1Locator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-4.MuiGrid-grid-lg-3.css-1hrvdsy > div > div > div:nth-child(2) > p',
        infoCard1Text2Locator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-4.MuiGrid-grid-lg-3.css-1hrvdsy > div > div > div:nth-child(3) > p',
        storeTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > form > div > div:nth-child(2)',
        storeDropdownLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > form > div > div:nth-child(2) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr > div',
        paymentTypeTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > form > div > div:nth-child(3)',
        paymentTypeDrowdownLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > form > div > div:nth-child(3) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr',
        orderTypeTitleLocator: '.MuiGrid-container > :nth-child(3) > .MuiTypography-root',
        orderNumberTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > form > div > div:nth-child(4)',
        orderNumberInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > form > div > div:nth-child(4) > div > div',
    },
    orderItemStepper:{
        iconLocator: '[Items"] > .MuiButtonBase-root > .MuiStepLabel-root > .MuiStepLabel-labelContainer > .MuiStepLabel-label',
        saveAndContinueButtonLocator: '.MuiButton-contained',
        backButtonLocator: '.custom-stepper-header-action-button > .MuiButton-outlined',
        shipmentItemsCardTittleLocator: '.display-flex-align-center.css-0 > .MuiTypography-root',
        nameInputTitleLocator:'.MuiGrid-grid-md-4 > .field-label-container > .MuiTypography-root',
        nameInputLocator:'#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div.display-flex.MuiBox-root.css-j250ce > div.MuiBox-root.css-1rr4qq7 > form > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.MuiGrid-grid-md-4.MuiGrid-grid-xl-6.css-1uqt7rq > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr > div',
        weightInputTitleLocator: ':nth-child(2) > :nth-child(1) > .MuiTypography-root',
        weightInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div.display-flex.MuiBox-root.css-j250ce > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(2) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr > div',
        priceInputTitleLocator: ':nth-child(3) > .field-label-container > .MuiTypography-root',
        priceInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div.display-flex.MuiBox-root.css-j250ce > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(3) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr > div',
        quantityInputTitleLocator: '.MuiGrid-grid-md-2 > .field-label-container > .MuiTypography-root',
        quantityInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div.display-flex.MuiBox-root.css-j250ce > div.MuiBox-root.css-1rr4qq7 > form > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.MuiGrid-grid-md-2.css-wubtha > div',
        addItemButtonLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div.display-flex.MuiBox-root.css-j250ce > div.ml-8.mb-1.mt-20.MuiBox-root.css-0 > button',  
        noItemPlaceHolder: '.css-1o749sn > img',
        notificationAlertLocator: '.display-flex-align-baseline > .MuiTypography-root',
        weightUnitDropDown: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div.display-flex.MuiBox-root.css-j250ce > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(2) > div > div > div > div',
        nameInputErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div.display-flex.MuiBox-root.css-j250ce > div.MuiBox-root.css-1rr4qq7 > form > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.MuiGrid-grid-md-4.MuiGrid-grid-xl-6.css-1uqt7rq > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr',
        weightInputErrorLocator: "#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div.display-flex.MuiBox-root.css-j250ce > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(2) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr",
        priceInputErrorLocator: "#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div.display-flex.MuiBox-root.css-j250ce > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(3) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr"
    },
    orderAddressStepper:{
        backToItemsButtonLocator: '.custom-stepper-header-action-button > :nth-child(1)',
        saveOrderButtonLocator: '.custom-stepper-header-action-button > .ml-8',
        saveAndContinueButtonLocator: '.MuiButton-contained',
        recipientAddressCardTitleLocator: '.MuiGrid-container > :nth-child(1) > .MuiTypography-root',
        countryInputTitleLocator: '.css-isbt42 > .MuiGrid-container > :nth-child(2) > .MuiTypography-root',
        countryInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div.MuiGrid-root.MuiGrid-container.MuiGrid-item.MuiGrid-spacing-xs-2.MuiGrid-grid-xs-12.display-flex-justify-space-between.css-1k82yfd > div:nth-child(2) > div > div',
        firstNameInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(2) > div.field-label-container.MuiBox-root.css-0',
        firstNameInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(2) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr > div',
        lastNameInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(3) > div.field-label-container.MuiBox-root.css-0',
        lastNameInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(3) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr > div',
        mobileNumberTitleInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(4) > div.field-label-container.MuiBox-root.css-0',
        mobileNumberInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(4) > div > div',
        emailInputTileLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(5) > div.field-label-container.MuiBox-root.css-0',
        emailInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(5) > div > div',
        bussinessInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(6) > div.field-label-container.MuiBox-root.css-0',
        bussinessInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(6) > div > div',
        address1InputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div.field-label-container.MuiBox-root.css-0',
        address1InputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(7) > div > div',
        address2InputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(8) > div.field-label-container.MuiBox-root.css-0',
        address2InputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(8) > div > div',
        landmarkInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(9) > div.field-label-container.MuiBox-root.css-0',
        landmarkInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(9) > div > div',
        pincodeInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(10) > div.field-label-container.MuiBox-root.css-0',
        pincodeInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(10) > div > div',
        cityInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(11) > div.field-label-container.MuiBox-root.css-0',
        cityInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(11) > div > div',
        stateInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(12) > p',
        stateInputLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(12) > div > div',
        locationForSameDayTitleLocator: '.display-flex-align-center > .css-falznv',
        addLatLongButtonLocator: '.display-flex-align-center > :nth-child(3)',
        editLatLongButtonLocator: '.display-flex-align-center > :nth-child(4)',
        removeLatLongButtonLocator: '.display-flex-align-center > :nth-child(5)',
        pickUpLocationCardTitleLocator: '.mb-8',
        pickUpLocationDropdownLocator: '.MuiStack-root > .ml-8',
        saveMapButtonLocator:'.display-flex-align-end > .ml-8',
        notificationAlertError: '.display-flex-align-baseline > .MuiTypography-root',
        editAdditionalAddressLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(4) > div > div > button',
        firstNameErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(2) > div',
        lastNameErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(3) > div',
        mobileErrorLocator:'#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(4) > div',
        emailErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(5) > div',
        businessErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(6) > div',
        address1ErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(7) > div',
        address2ErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(8) > div',
        landmarkErrorLocator:'#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(9) > div',
        pincodeErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(10) > div',
        cityErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(11) > div',
        stateErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div:nth-child(1) > div > form > div > div:nth-child(12) > div',
    },
    orderPackagingStepper:{
        backToRecipeintButtonLocator: '.custom-stepper-header-action-button > :nth-child(1)',
        unitButtonLocator: '.custom-stepper-header-action-button > .ml-8',
        saveAndContinueButtonLocator: '.MuiButton-contained',
        infoCardPlaceholdertext: '.MuiTypography-alignCenter > .css-falznv',
        packagesCardTitleLocator: '.height-100-perc > :nth-child(1) > .MuiTypography-root',
        specialServiceCardTitleLocator: '.display-flex-align-center > .MuiTypography-root',
        specialServiceIngoIconLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div:nth-child(3) > div > div > div.display-flex-justify-space-between.px-16.MuiBox-root.css-0 > div > button > svg',
        typeInputTitleLocator: '.MuiGrid-grid-sm-3 > .MuiTypography-root',
        typeInputLocator: 'div.MuiFormControl-root input[type="text"]',
        lengthInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div > div.MuiBox-root.css-10ib5jr > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(2) > div.field-label-container.MuiBox-root.css-0',
        lengthInputLocator: '[fieldname="length"] input[type="number"]',
        widthInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div > div.MuiBox-root.css-10ib5jr > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(3) > div.field-label-container.MuiBox-root.css-0',
        widthInputLocator: '[fieldname="width"] input[type="number"]',
        heightInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div > div.MuiBox-root.css-10ib5jr > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(4) > p',
        heightInputLocator: '[fieldname="height"] input[type="number"]',
        weightInputTitleLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div > div.MuiBox-root.css-10ib5jr > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(5) > div.field-label-container.MuiBox-root.css-0',
        weightInputLocator: '[fieldname="weight"] input[type="number"]',
        qtyInputTitleLocator: 'p.MuiTypography-root.MuiTypography-body1.required.css-falznv',
        qtyInputLocator: '[fieldname="quantity"] input[type="number"]',
        addPackageButtonLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div > div.MuiBox-root.css-10ib5jr > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.ml-8.mb-1.mt-20.MuiBox-root.css-0 > button',
        insuranceTitleLocator: '.display-flex-justify-center > .MuiTypography-body1 > .MuiTypography-root',
        codTitleLocator: ':nth-child(2) > .display-flex-justify-center > .MuiTypography-root',
        hazmatTitleLocator: '.css-1d3bbye > .MuiGrid-container > :nth-child(3) > .MuiTypography-root',
        liquidContentTitleLocator: '.css-1d3bbye > .MuiGrid-container > :nth-child(4) > .MuiTypography-root',
        fragileTitleLocator: '.css-1d3bbye > .MuiGrid-container > :nth-child(5) > .MuiTypography-root',
        otpRequiredTitleLocator: ':nth-child(6) > .MuiTypography-root',
        specialServiceInfoLocator: '.special-service-info-text',
        lengthErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div > div.MuiBox-root.css-10ib5jr > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(2) > div',
        widthErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div > div.MuiBox-root.css-10ib5jr > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(3) > div',
        heightErrorLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div > div.MuiBox-root.css-10ib5jr > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(4) > div',
        notificationAlertLocator: '.display-flex-align-baseline > .MuiTypography-root',
        deletePackageIcon: '.MuiButtonBase-root > .MuiAvatar-root > .MuiAvatar-img',
        deletePackageConfirmButton: '.MuiButton-contained > .MuiTypography-root',
    },
    orderCarrierStepper:{
        backToPackagingButtonLocator: '.MuiButton-outlined',
        saveAndContinueButtonLocator: '.MuiButton-contained',
        selectedRateCardLogo: '.selected-feature-card > .MuiAvatar-root > .MuiAvatar-img',
        selectedRateCardLocator: '.selected-feature-card',
        selectedRateCardCarrierName: '.selected-feature-card > .shipment-rate-card-title',
        selectedRateCardTotalFee: '.selected-feature-card > :nth-child(5)',
        selectedRateCardEDD: '.selected-feature-card > .css-n8z4i6',
        selectRateCardPackageWeight: '.selected-feature-card > .display-flex-justify-center.css-1bu4qnu'
    },
    orderComplianceStepper:{
        saveAndContinueButtonLocator: '.MuiButton-contained',
        typeDropdownLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.MuiBox-root.css-1rr4qq7 > form > div > div:nth-child(1) > div > div',
        numberInputLocator: '[fieldname="number"] input[type="text"]',
        amountInputLocator: '[fieldname="value"] input[type="text"]',
        fileInputBrowserButton: 'input[type="file"][accept*=".PDF"]',
        addDocsButtonLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.MuiBox-root.css-1dc6lqx > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > div > div > div.display-flex.MuiBox-root.css-1yuhvjn > div.ml-8.mb-1.mt-20.MuiBox-root.css-0 > button',
        notificationAlertLocator: '.display-flex-align-baseline > .MuiTypography-root',
    },
    orderReviewStepper:{
        backToCarrierButtonLocator: '.MuiButton-outlined',
        createShipmentButtonLocator: '.MuiButton-contained',
        itemsCardTitleLocator: '.MuiStack-root > .MuiTypography-root',
        firstitemLocator:'.css-obit8q > .MuiGrid-grid-xs-12',
        addressesCardTitleLocator: '.css-1fdqhw5 > .MuiTypography-root',
        packagingAndCarrierCardTitleLocator: '.MuiGrid-root > .MuiTypography-root',
        trackingCardTitleLocator: '.display-flex-justify-space-between > .MuiTypography-root',
        recipientAddressTitleLocator: ':nth-child(3) > .css-mtcwej',
        recipientAddressCardLocator: ':nth-child(2) > .MuiPaper-root > :nth-child(1) > :nth-child(3)',
        pickupLocationTitleLocator: ':nth-child(4) > .css-mtcwej',
        pickupLocationCardLocator: ':nth-child(2) > .MuiPaper-root > :nth-child(1) > :nth-child(4)',
        boxTitleLocator: ':nth-child(3) > .css-1rr4qq7 > .display-flex > .MuiTypography-noWrap',
        weightTitleLocator: ':nth-child(3) > .css-1rr4qq7 > :nth-child(2) > .css-8fbmue',
        billableTitleLocator: ':nth-child(3) > .css-1rr4qq7 > :nth-child(3) > .css-8fbmue',
        carrierNameAndSeviceTitleLocator: ':nth-child(4) > .css-1rr4qq7 > .display-flex > .MuiTypography-noWrap',
        eddTitleLocator: ':nth-child(4) > .css-1rr4qq7 > :nth-child(2) > .css-8fbmue',
        supporetedContactTitleLocator: ':nth-child(4) > .css-1rr4qq7 > :nth-child(3) > .css-8fbmue',
        totalFeeTitleLocator: ':nth-child(5) > .css-1rr4qq7 > .display-flex > .MuiTypography-noWrap',
        notificationAlertLocator: '.display-flex-align-baseline > .MuiTypography-root',
        trackingNumberlocator: '.display-flex-align-center > :nth-child(10)',
        moreOptionsButtonLocator: '.MuiButton-outlined',
        cloneOrderButtonLocator: '.MuiButton-contained'
    },
    shipmentList:{
    },
    orderPendingDetail:{
        fulfillOrderButtonLocator: '.MuiButton-contained',
        discardOrderButtonLocator: '.MuiGrid-grid-sm-4 > .mr-4',
        discardPopupConfirmButtonLocator: '.MuiButton-contained > .MuiTypography-root',
        notificationAlertLocator: '.display-flex-align-baseline > .MuiTypography-root',
    },
    orderImportPopup:{
        uploadImportFileLocator:'.dashed-border-import-info',
        uploadButtonLocator: '.css-0 > .MuiButton-contained',
        notificationAlertLocator: '.display-flex-align-baseline > .MuiTypography-root',
        closeImportPopButtonLocator: '.css-0 > .mr-4'
    },
    manageGeneral:{
        accountFeatureCardLocator: '.manage-setting-card > .MuiBox-root > :nth-child(1)',
        userFeatureCardLocator: '.manage-setting-card > .MuiBox-root > :nth-child(2)',
        pickLocationFeatureCardLocator: '.manage-setting-card > .MuiBox-root > :nth-child(3)',
        packageTypesFeatureCardLocator: '.manage-setting-card > .MuiBox-root > :nth-child(4)'
    },
    manageIntegrations:{
        integrationsTabLocator: '.css-tiqdez',
        clickStoresFeatureCardLocator: '.manage-setting-card > .MuiBox-root > :nth-child(1)',
    },
    packageTypes:{
        firstPackageTypeInListLocator: '#root > div > main > div > div > div.main-card-content.MuiBox-root.css-19n8dai > div.tab-list-container.MuiBox-root.css-0 > div > div.MuiTableContainer-root.tab-list-table-container.css-kge0eu > table > tbody > tr:nth-child(1)',
        addPackageTypesButtonLocator:'.MuiButton-contained',
        savePackageTypesButtonLocator:'.MuiButton-contained',
        updatePackageTypesButtonLocator:'.MuiButton-contained',
        nameInputLocator:'[fieldname="name"] input[type="text"]',
        typeInputLocator:'.MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root',
        lengthInputLocator:'[fieldname="length"] input[type="number"]',
        widthInputLocator:'[fieldname="width"] input[type="number"]',
        heightInputLocator:'[fieldname="height"] input[type="number"]',
        weightInputLocator:'[fieldname="weight"] input[type="number"]',
        moreVertButtonLocator: ':nth-child(1) > :nth-child(7) > .display-flex-align-center-justify-flex-end > .css-1yxmbwk',
        overFlowMenuDeleteButtonLocator:'[label="Delete"]',
        notificationAlertLocator: '.display-flex-align-baseline > .MuiTypography-root',
    },
    pickupLocation:{
        firstPickupLocationInListLocator: '#root > div > main > div > div > div.main-card-content.MuiBox-root.css-19n8dai > div.tab-list-container.MuiBox-root.css-0 > div > div.MuiTableContainer-root.tab-list-table-container.css-kge0eu > table > tbody > tr:nth-child(1)',
        addPickupLocationButtonLocator:'.MuiButton-contained',
        savePickupLocationButtonLocator:'.MuiButton-contained',
        updatePickupLocationButtonLocator:'.MuiButton-contained',
        locationNameInputLocator:'[fieldname="locationName"] input[type="text"]',
        firstNameInputLocator:'[fieldname="firstName"] input[type="text"]',
        lastNameInputLocator:'[fieldname="lastName"] input[type="text"]',
        mobileNumberInputLocator:'#root > div > main > div > div > div.main-card-content.MuiBox-root.css-19n8dai > div.MuiGrid-root.MuiGrid-container.MuiGrid-spacing-xs-2.height-100-perc.css-191zoks > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > form > div > div:nth-child(4) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-ltwxtn > div > input[type="text"]',
        emailInputLocator:'[fieldname="email"] input[type="text"]',
        bussinessInputLocator:'[fieldname="company"] input[type="text"]',
        address1InputLocator:'#root > div > main > div > div > div.main-card-content.MuiBox-root.css-19n8dai > div.MuiGrid-root.MuiGrid-container.MuiGrid-spacing-xs-2.height-100-perc.css-191zoks > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-8.MuiGrid-grid-lg-9.css-1cp9ys7 > div > form > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6.css-rpybyc > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-159m7hr > div',
        address2InputLocator:'[fieldname="street2"] input[type="text"]',
        landmarkInputLocator:'[fieldname="street3"] input[type="text"]',
        pincodeInputLocator:'[fieldname="zip"] input[type="text"]',
        saveMapButtonLocator: '.display-flex-align-end > .ml-8',
        addLatLongButtonLocator:'.display-flex-align-center > :nth-child(3)',
        moreVertButtonLocator: '#root > div > main > div > div > div.main-card-content.MuiBox-root.css-19n8dai > div.tab-list-container.MuiBox-root.css-0 > div > div.MuiTableContainer-root.tab-list-table-container.css-kge0eu > table > tbody > tr:nth-child(1) > td.MuiTableCell-root.MuiTableCell-body.MuiTableCell-alignRight.MuiTableCell-sizeMedium.css-1i36psw > button',
        overFlowMenuDeleteButtonLocator:'[label="Delete"]',
        notificationAlertLocator: '.display-flex-align-baseline > .MuiTypography-root',
    },
    users:{
        firstUserInListLocator: '#root > div > main > div > div > div.main-card-content.MuiBox-root.css-19n8dai > div.tab-list-container.MuiBox-root.css-0 > div > div.MuiTableContainer-root.tab-list-table-container.css-kge0eu > table > tbody > tr:nth-child(1)',
        addUserButtonLocator:'.MuiButton-contained',
        saveUserButtonLocator:'.MuiButton-contained',
        updateUserButtonLocator:'.MuiButton-contained',
        firstNameInputLocator:'[fieldname="firstName"] input[type="text"]',
        lastNameInputLocator:'[fieldname="lastName"] input[type="text"]',
        roleInputLocator: '[fieldname="role"]',
        mobileNumberInputLocator:'#root > div > main > div > div > div.main-card-content.MuiBox-root.css-19n8dai > div.px-16.MuiBox-root.css-1rr4qq7 > div > form > div > div:nth-child(3) > div.MuiFormControl-root.MuiFormControl-fullWidth.MuiTextField-root.hide-input-number-arrow.css-ltwxtn > div> input[type="text"]',
        emailInputLocator:'[fieldname="email"] input[type="text"]',
        moreVertButtonLocator: '#root > div > main > div > div > div.main-card-content.MuiBox-root.css-19n8dai > div.tab-list-container.MuiBox-root.css-0 > div > div.MuiTableContainer-root.tab-list-table-container.css-kge0eu > table > tbody > tr:nth-child(1) > td.MuiTableCell-root.MuiTableCell-body.MuiTableCell-alignRight.MuiTableCell-sizeMedium.css-1i36psw > button',
        overFlowMenuDeleteButtonLocator:'[label="Delete"]',
        notificationAlertLocator: '.display-flex-align-baseline > .MuiTypography-root',
        createPasswordMailButtonLocator: 'a:contains("Create Password")',
        newPasswordInputLocator: '#reset-password-new',
        confirmPasswordInputLocator: '#reset-password-confirm',
        createPasswordButtonLocator: '#reset-password-btn-text',
    },
    stores:{
        firstStoreInListLocator:'#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.tab-list-container.MuiBox-root.css-0 > div > div.MuiTableContainer-root.tab-list-table-container.css-kge0eu > table > tbody > tr:nth-child(1)',
        addStoreButtonLocator:'.MuiButton-contained',
        saveStoreButtonLocator:'.MuiButton-contained',
        updateStoreButtonLocator:'.MuiButton-contained',
        manualStoreTypeButtonLocator: '.store-card-container > :nth-child(2)',
        storNameInputLocator: '[fieldname="name"] input[type="text"]',
        moreVertButtonLocator: '#root > div > main > div > div.main-card-content.MuiBox-root.css-0 > div.tab-list-container.MuiBox-root.css-0 > div > div.MuiTableContainer-root.tab-list-table-container.css-kge0eu > table > tbody > tr:nth-child(1) > td.MuiTableCell-root.MuiTableCell-body.MuiTableCell-alignRight.MuiTableCell-sizeMedium.css-1i36psw > button',
        notificationAlertLocator:'.display-flex-align-baseline > .MuiTypography-root',
    },
    muiSelectors:{
        drowdownOptions: 'ul[role="listbox"] li',
        snackBarMessage: '.MuiAlert-message'
    }


}